## Convesion of string data into numarical data


In [38]:
sent1 = "It is good for our progress"
sent2 = "It is bad for our progress"

In [39]:
from sklearn.feature_extraction.text import CountVectorizer

In [40]:
cvt = CountVectorizer()

In [41]:
vect = cvt.fit_transform([sent1, sent2])

In [42]:
import pandas as pd

In [43]:
df = pd.DataFrame(vect.toarray(), columns=cvt.get_feature_names_out())
df

bad  for  good  is  it  our  progress
0    0    1     1   1   1    1         1
1    1    1     0   1   1    1         1

### Continud bag of words

In [44]:
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [45]:
lines = ['It was a nice rainy day', ' the things are so beautiful in his point', 'when your fpcis os clear, you won', 'many many happy returns of the day' ]

In [46]:
lines[0].split()

['It', 'was', 'a', 'nice', 'rainy', 'day']

In [47]:
tokanizer = Tokenizer()
tokanizer.fit_on_texts(lines)

In [48]:
tokanizer.word_counts

OrderedDict([('it', 1),
             ('was', 1),
             ('a', 1),
             ('nice', 1),
             ('rainy', 1),
             ('day', 2),
             ('the', 2),
             ('things', 1),
             ('are', 1),
             ('so', 1),
             ('beautiful', 1),
             ('in', 1),
             ('his', 1),
             ('point', 1),
             ('when', 1),
             ('your', 1),
             ('fpcis', 1),
             ('os', 1),
             ('clear', 1),
             ('you', 1),
             ('won', 1),
             ('many', 2),
             ('happy', 1),
             ('returns', 1),
             ('of', 1)])

In [49]:
tokanizer.word_index

{'day': 1,
 'the': 2,
 'many': 3,
 'it': 4,
 'was': 5,
 'a': 6,
 'nice': 7,
 'rainy': 8,
 'things': 9,
 'are': 10,
 'so': 11,
 'beautiful': 12,
 'in': 13,
 'his': 14,
 'point': 15,
 'when': 16,
 'your': 17,
 'fpcis': 18,
 'os': 19,
 'clear': 20,
 'you': 21,
 'won': 22,
 'happy': 23,
 'returns': 24,
 'of': 25}

In [50]:
mat = tokanizer.texts_to_matrix(lines)
mat  #bag of words (no sequence)

array([[0., 1., 0., 0., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 1., 1., 1.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 1., 1., 1.]])

In [51]:
seq = tokanizer.texts_to_sequences(lines)
seq

[[4, 5, 6, 7, 8, 1],
 [2, 9, 10, 11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20, 21, 22],
 [3, 3, 23, 24, 25, 2, 1]]

In [52]:
#padding, making all rows equal (adding zeros...) [pre/post]
padded = pad_sequences(seq, padding='pre')
padded

array([[ 0,  0,  4,  5,  6,  7,  8,  1],
       [ 2,  9, 10, 11, 12, 13, 14, 15],
       [ 0, 16, 17, 18, 19, 20, 21, 22],
       [ 0,  3,  3, 23, 24, 25,  2,  1]], dtype=int32)

## Actual Program Starts Here

In [53]:
import re
import pandas as pd

In [54]:
#download twitter sentiments.csv
data = pd.read_csv("twitter_sentiments.csv", names=['id', 'loc', 'label', 'text'])
data

id          loc     label  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   
74681  9200       Nvidia  Positive   

                                                    text  
0      im getting on borderlands and i will murder yo...  
1      I am coming to the borders and I will kill you...  
2      im getting on borderlands and i will kill you ...  
3      im coming on borderlands and i will murder you...  
4      im getting on borderlands 2 and i will murder ...  
...                                                  ...  
74677  Just realized that the Windows partition of my...  
74678  Just realized that my Mac window partition is ...  
74679  Just realized the windows partition of my Mac ...  
74680  Just realized between the windows partition of...  
74681  Just like the windows partition of my Mac is l...  

[74682 rows x 4 columns]

In [55]:
data.shape


(74682, 4)

In [56]:
data.dtypes

id        int64
loc      object
label    object
text     object
dtype: object

In [57]:
data['text'] = data['text'].astype(str)

In [58]:
data.dtypes

id        int64
loc      object
label    object
text     object
dtype: object

In [59]:
#clening of text
def clean_text(text):
  text = text.lower() #lowercase
  text = re.sub(r"[^a-zA-Z]+", " ", text) #remove non-aplhanumric chars
  return text

In [60]:
clean_text("hello @3423432 friends, im fine;;;;")

'hello friends im fine '

In [61]:
data['text'] = data['text'].apply(clean_text)

In [62]:
data

id          loc     label  \
0      2401  Borderlands  Positive   
1      2401  Borderlands  Positive   
2      2401  Borderlands  Positive   
3      2401  Borderlands  Positive   
4      2401  Borderlands  Positive   
...     ...          ...       ...   
74677  9200       Nvidia  Positive   
74678  9200       Nvidia  Positive   
74679  9200       Nvidia  Positive   
74680  9200       Nvidia  Positive   
74681  9200       Nvidia  Positive   

                                                    text  
0      im getting on borderlands and i will murder yo...  
1      i am coming to the borders and i will kill you...  
2      im getting on borderlands and i will kill you ...  
3      im coming on borderlands and i will murder you...  
4      im getting on borderlands and i will murder yo...  
...                                                  ...  
74677  just realized that the windows partition of my...  
74678  just realized that my mac window partition is ...  
74679  just realized the windows partition of my mac ...  
74680  just realized between the windows partition of...  
74681  just like the windows partition of my mac is l...  

[74682 rows x 4 columns]

In [63]:
comments = data['text'].tolist()
targets=data['label'].values

In [64]:
pd.DataFrame(targets).value_counts()

0         
Negative      22542
Positive      20832
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [65]:
# Tokanization and padding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(num_words = 5000)
tokenizer.fit_on_texts(comments)
sequences = tokenizer.texts_to_sequences(comments)
padded_sequences = pad_sequences(sequences, maxlen=200)

In [66]:
padded_sequences.shape

(74682, 200)

In [67]:
padded_sequences

array([[   0,    0,    0, ..., 1695,   12,   26],
       [   0,    0,    0, ...,  424,   12,   26],
       [   0,    0,    0, ...,  424,   12,   26],
       ...,
       [   0,    0,    0, ...,  302,   15, 2055],
       [   0,    0,    0, ...,  302,   15, 2055],
       [   0,    0,    0, ...,  302,   15, 2055]], dtype=int32)

In [68]:
#label encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(targets)

#one hot encoding
from keras.utils import to_categorical
y_new = to_categorical(y)

In [69]:
y_new

array([[0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       ...,
       [0., 0., 0., 1.],
       [0., 0., 0., 1.],
       [0., 0., 0., 1.]])

In [70]:
#train test split/ cross validation
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(padded_sequences, y_new, test_size=0.2, random_state=0)

In [71]:
x_train.shape

(59745, 200)

In [76]:
x_test.shape

(14937, 200)

## Train Model

In [77]:
# model definition (cutomized architecture)
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

model = Sequential()
model.add(Embedding(5000, 128))
model.add(LSTM(64))
model.add(Dense(4, activation='softmax'))
#multi label output

In [78]:
#compilation
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [79]:
model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=10, batch_size=32)

Epoch 1/10
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 22s 11ms/step - accuracy: 0.5404 - loss: 1.0700 - val_accuracy: 0.6993 - val_loss: 0.7670
Epoch 2/10
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 21s 11ms/step - accuracy: 0.7553 - loss: 0.6331 - val_accuracy: 0.7612 - val_loss: 0.6184
Epoch 3/10
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 24s 13ms/step - accuracy: 0.8260 - loss: 0.4564 - val_accuracy: 0.7870 - val_loss: 0.5606
Epoch 4/10
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 20s 11ms/step - accuracy: 0.8714 - loss: 0.3449 - val_accuracy: 0.8201 - val_loss: 0.5018
Epoch 5/10
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 21s 11ms/step - accuracy: 0.8938 - loss: 0.2759 - val_accuracy: 0.8270 - val_loss: 0.5093
Epoch 6/10
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 21s 11ms/step - accuracy: 0.9123 - loss: 0.2229 - val_accuracy: 0.8354 - val_loss: 0.5161
Epoch 7/10
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 21s 11ms/step - accuracy: 0.9239 - loss: 0.1899 - val_accuracy: 0.8421 - val_loss: 0.5227
Epoch 8/10
1868/1868 ━━━━━━━━━━━━━━━━━━━━ 41s 11ms/step - accuracy: 0.9344 -

In [91]:
## Output

new_comment = "I like him, saying this sentense is wrong thing..."
new_sequence = tokenizer.texts_to_sequences([clean_text(new_comment)])
padded_new_sequence = pad_sequences(new_sequence, maxlen=200)
prediction = model.predict(padded_new_sequence)[0]

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step


In [92]:
prediction


array([0.8774172 , 0.03144817, 0.02794706, 0.06318757], dtype=float32)

In [93]:
import numpy as np

le.inverse_transform([np.argmax(prediction)])

array(['Irrelevant'], dtype=object)